// <auto-generated />
using System;
using ElectricalCarStoreApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectricalCarStoreApi.Migrations
{
    [DbContext(typeof(CarDb))]
    [Migration("20221124115405_NewFields")]
    partial class NewFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("ElectricalCarStoreApi.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "brand");

                    b.Property<string>("City")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "city");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "color");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "imageUrl");

                    b.Property<decimal>("KilometersDriven")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "kilometersDriven");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "manufactureYear");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "model");

                    b.Property<int>("ModelYear")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "modelYear");

                    b.Property<string>("PlateLastNumber")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "plateLastNumber");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "price");

                    b.Property<string>("TransmissionType")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "transmissionType");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
